name: iwms_citizen_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Using a compatible SDK range

dependencies:
  flutter:
    sdk: flutter
  
  # --- Keep Device Preview ---
  device_preview: ^1.1.0 # You can use your exact version

  # --- Core App Packages (From your repo) ---
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  equatable: ^2.0.7
  
  # --- Map Packages (From your repo - UNTOUCHED) ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # --- Local Storage (From your repo - for Auth) ---
  shared_preferences: ^2.5.3 

  # --- NEW: Font package for our theme ---
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_bg.png" 
  min_sdk_android: 21
  
flutter:
  uses-material-design: true

  # --- Assets (From your repo - UNTOUCHED) ---
  assets:
    - assets/images/logo.png
    - assets/images/logo_bg.png
    - assets/images/zigma.png
    - assets/images/blueplanet.png
    - assets/images/w_waste.png
    - assets/images/d_waste.png
    - assets/images/m_waste.png
    - assets/images/qr.png
    - assets/images/bg.png