name: iwms_citizen_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core App Packages ---
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  equatable: ^2.0.7
  
  # --- UI & Utilities ---
  device_preview: ^1.1.0 
  google_fonts: ^6.2.1        # <-- UPGRADED
  shared_preferences: ^2.5.3 
  
  # --- Module 1 (Citizen) Packages ---
  flutter_map: ^7.0.1          # <-- UPGRADED
  latlong2: ^0.9.1            # <-- UPGRADED
  
  # --- Module 2 (Driver) Packages ---
  mobile_scanner: ^6.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2        # <-- UPGRADED
  permission_handler: ^12.0.1
  # http: ^0.13.3              # <-- REMOVED
  # image: ^3.0.1              # <-- REMOVED (Let flutter_launcher_icons handle its own version)
  path_provider: ^2.1.4
  flutter_image_compress: ^2.4.0
  flutter_bluetooth_serial: ^0.4.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # <-- UPGRADED
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_bg.png" 
  min_sdk_android: 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_bg.png
    - assets/images/zigma.png
    - assets/images/blueplanet.png
    - assets/images/w_waste.png
    - assets/images/d_waste.png
    - assets/images/m_waste.png
    - assets/images/qr.png
    - assets/images/bg.png
    - assets/images/driver_logo.png
